Account:
    Username: sample
    Password: sample
Files:
    Cache: config_cache.json
    XMLTV: config.xml
    The MovieDB cache file: config_tmdb_cache.json
Server:
    Enable: false
    Address: localhost
    Port: "80"
Options:
    Schedule Days: 1
    Subtitle into Description: false
    Insert credits tag into XML file: false
    Images:
        Download Images: false
        Image Path: ""
        Proxy Mode: false
        Proxy Base URL: ""
        Max Cache Age Days: 0
        Purge Stale Posters: false
        The MovieDB:
            Enable: false
            Api Key: ""
    Rating:
        Insert rating tag into XML file: false
        Maximum rating entries. 0 for all entries: 1
        Preferred countries. ISO 3166-1 alpha-3 country code. Leave empty for all systems:
            - USA
        Use country code as rating system: false
    Show download errors from Schedules Direct in the log: false
Station:
    - Name: WGBO-DT
      ID: "42635"
      Lineup: USA-IL67050-X
